### ISSUE TITLE
Licence file?

### ISSUE THREAD

**Issue by badrihippo** [dbr/pyfeedproc#1]
Are you planning to add a LICENCE file to this project?

I know it's not maintained, but it could still be useful for people (like me!) working on RSS parsing. Having an open licence would make it easier to reuse the code.

**Comment by dbr** [comment]
Good point - added!

**Comment by badrihippo** [comment]
I just realised you *did* mark the code public domain in `feedproc.py` already. I guess this will make it easier, though.

Maybe you could mention that `PyRSS2Gen.py` and 'feedparser.py` are external code with their own licenses (although any good person should be able to figure that out). Licensing is tricky, as I just realised :stuck_out_tongue:
